### ISSUE TITLE
Convert Observable without objects

### ISSUE THREAD

**Issue by chehsunliu** [oasis-open/cti-stix-elevator#128]
I used the sample code from the [official](https://github.com/STIXProject/stixproject.github.io/blob/master/documentation/concepts/composition/observable_composition.py) and generated the following STIX report.

`sample.xml`:

```xml
<stix:STIX_Package 
        xmlns:FileObj="http://cybox.mitre.org/objects#FileObject-2"
        xmlns:EmailMessageObj="http://cybox.mitre.org/objects#EmailMessageObject-2"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
        xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2"
        xmlns:SocketAddressObj="http://cybox.mitre.org/objects#SocketAddressObject-1"
        xmlns:MutexObj="http://cybox.mitre.org/objects#MutexObject-2"
        xmlns:stix="http://stix.mitre.org/stix-1"
        xmlns:cybox="http://cybox.mitre.org/cybox-2"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:example="http://example.com"
        xmlns:NetworkConnectionObj="http://cybox.mitre.org/objects#NetworkConnectionObject-2"
        xmlns:AddressObj="http://cybox.mitre.org/objects#AddressObject-2"
        xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
        xmlns:xlink="http://www.w3.org/1999/xlink"
         id="example:Package-26c6af28-3cec-4741-aec6-23d9866ab1fa" version="1.1.1">
    <stix:Observables cybox_major_version="2" cybox_minor_version="1" cybox_update_version="0">
        <cybox:Observable id="example:Observable-2835582e-d8da-488e-b5d8-fa39e9dce4c2">
            <cybox:Object id="example:File-9f455bda-a4d8-4b59-a101-3a323d78fe31">
                <cybox:Properties xsi:type="FileObj:FileObjectType">
                    <FileObj:File_Name condition="Contains">foo.exe</FileObj:File_Name>
                </cybox:Properties>
            </cybox:Object>
        </cybox:Observable>
        <cybox:Observable id="example:Observable-aee501ef-918f-42fd-acec-05124b723b40">
            <cybox:Object id="example:File-f07e858e-d950-479e-a176-aed948021bef">
                <cybox:Properties xsi:type="FileObj:FileObjectType">
                    <FileObj:File_Name condition="Contains">foo</FileObj:File_Name>
                    <FileObj:Size_In_Bytes condition="Equals">1896000</FileObj:Size_In_Bytes>
                </cybox:Properties>
            </cybox:Object>
        </cybox:Observable>
        <cybox:Observable id="example:Observable-7374a799-a5ad-46b9-b252-f62bd44ed35b">
            <cybox:Object id="example:EmailMessage-05266b6f-c457-4a23-af1c-7324a3dc2d26">
                <cybox:Properties xsi:type="EmailMessageObj:EmailMessageObjectType">
                    <EmailMessageObj:Header>
                        <EmailMessageObj:Subject condition="Equals">Syria strategic plans leaked</EmailMessageObj:Subject>
                    </EmailMessageObj:Header>
                </cybox:Properties>
                <cybox:Related_Objects>
                    <cybox:Related_Object id="example:File-6110d096-91db-4480-8a8a-6c068b58f021">
                        <cybox:Properties xsi:type="FileObj:FileObjectType">
                            <FileObj:File_Name condition="Equals">bombISIS.pdf</FileObj:File_Name>
                        </cybox:Properties>
                        <cybox:Relationship xsi:type="cyboxVocabs:ObjectRelationshipVocab-1.1">Contains</cybox:Relationship>
                    </cybox:Related_Object>
                </cybox:Related_Objects>
            </cybox:Object>
        </cybox:Observable>
        <cybox:Observable id="example:Observable-f31992a7-ab34-4d41-9d50-4d96d692dc0b">
            <cybox:Observable_Composition operator="AND">
                <cybox:Observable id="example:Observable-fbd1c1e1-b566-400f-a270-faac7996bf19">
                    <cybox:Observable_Composition operator="OR">
                        <cybox:Observable id="example:Observable-685da731-6b98-4e4f-ba01-cdf61a777579">
                            <cybox:Object id="example:Mutex-e529fa49-88ff-43bc-9724-83fad848a015">
                                <cybox:Properties xsi:type="MutexObj:MutexObjectType">
                                    <MutexObj:Name condition="Contains">foo</MutexObj:Name>
                                </cybox:Properties>
                            </cybox:Object>
                        </cybox:Observable>
                        <cybox:Observable id="example:Observable-8cb76217-49d6-4a27-a496-cc771f6f4894">
                            <cybox:Object id="example:File-eba68e1d-01e1-4a11-9afc-3df1a268d6cb">
                                <cybox:Properties xsi:type="FileObj:FileObjectType">
                                    <FileObj:File_Name condition="Equals">barfoobar</FileObj:File_Name>
                                </cybox:Properties>
                            </cybox:Object>
                        </cybox:Observable>
                    </cybox:Observable_Composition>
                </cybox:Observable>
                <cybox:Observable id="example:Observable-23343a75-ee8a-48b3-a78e-65587130d885">
                    <cybox:Object id="example:NetworkConnection-7a09758d-b1ae-4b27-bcc5-9509b955d8b0">
                        <cybox:Properties xsi:type="NetworkConnectionObj:NetworkConnectionObjectType">
                            <NetworkConnectionObj:Destination_Socket_Address xsi:type="SocketAddressObj:SocketAddressObjectType">
                                <SocketAddressObj:IP_Address xsi:type="AddressObj:AddressObjectType" category="ipv4-addr">
                                    <AddressObj:Address_Value condition="Equals">46.123.99.25</AddressObj:Address_Value>
                                </SocketAddressObj:IP_Address>
                            </NetworkConnectionObj:Destination_Socket_Address>
                        </cybox:Properties>
                    </cybox:Object>
                </cybox:Observable>
            </cybox:Observable_Composition>
        </cybox:Observable>
        <cybox:Observable id="example:Observable-260243c4-50d5-46e7-a73d-622f075a7444">
            <cybox:Object id="example:SocketAddress-c9f01d2d-886a-4ad5-a186-cb8a00b86ace">
                <cybox:Properties xsi:type="SocketAddressObj:SocketAddressObjectType">
                    <SocketAddressObj:IP_Address xsi:type="AddressObj:AddressObjectType">
                        <AddressObj:Address_Value condition="Equals" apply_condition="ANY">10.0.0.0##comma##10.0.0.1##comma##10.0.0.2</AddressObj:Address_Value>
                    </SocketAddressObj:IP_Address>
                </cybox:Properties>
            </cybox:Object>
        </cybox:Observable>
    </stix:Observables>
</stix:STIX_Package>
```

I then ran the command `stix2_elevator sample.xml` and got an exception:

```
Traceback (most recent call last): 
  File "/usr/bin/stix2_elevator", line 11, in <module> 
    load_entry_point('stix2-elevator==1.1.3', 'console_scripts', 'stix2_elevator')() 
  File "/usr/lib/python2.7/site-packages/stix2elevator/cli.py", line 183, in main
     result = elevate_file(elevator_args.file_)
   File "/usr/lib/python2.7/site-packages/stix2elevator/__init__.py", line 63, in elevate_file
     get_option_value("default_timestamp")), 
  File "/usr/lib/python2.7/site-packages/stix2elevator/convert_stix.py", line 1730, in convert_package 
    o_d20 = convert_observed_data(o_d, bundle_instance, package_created_by_ref, parent_timestamp)
   File "/usr/lib/python2.7/site-packages/stix2elevator/convert_stix.py", line 1117, in convert_observed_data
     observed_data_instance["objects"] = convert_cybox_object(obs.object_)
   File "/usr/lib/python2.7/site-packages/stix2elevator/convert_cybox.py", line 464, in convert_cybox_object 
    prop = obj.properties
 AttributeError: 'NoneType' object has no attribute 'properties'
```

It seems the library does not handle the case that an Observable contains an Observable_Composition only.

**Comment by rpiazza** [comment]
Thanks for the issue, @chehsunliu 

I get the same error.  We are planning a new release of the elevator soon, so I will make sure a fix for this is included.

**Comment by rpiazza** [comment]
@chehsunliu,

The more I look at that example, the more I'm convinced that even though it is legal syntactically, its meaning semantically is confusing in STIX 1.x and not really representable in STIX 2.0.

Observable compositions only make sense in the context of an Indicator pattern.  Things get confusing since the same syntax is used for observations and patterns in STIX 1.x.  In STIX 2.0 observables (things seen) are represented by Observed Data, and patterns (things to look for) are represented differently using the pattern language in part 5 of the specification.

But even in STIX 1.x, observable compositions outside the context of a indicator pattern isn't well defined.  What could it mean to say you saw obs1 OR obj2?  Since observables supposed to represent facts, things _actually_ observed, that makes little sense.  Additionally, all observables can be though of as ANDed together - they are all things observed.

This is a long way of saying, that the elevator will not be changed to support this questionable STIX 1.x.  I do plan to change the example script so it makes more sense, but otherwise, I am closing the issue.

Feel free to reopen it if you have other comments.
