### ISSUE TITLE
lxml.etree.XMLSyntaxError: Document is empty

### ISSUE THREAD

**Issue by arcsector** [oasis-open/cti-stix-elevator#159]
Sorry to do this to you again, guys, but this seems to be a problem with the stix 1 validator as well, but I solved it there so I wanted to ask if you guys could help with this. I'm getting a weird `lxml` error. Could this be because there aren't any compatible mappings for anything in the file:
```
[stixmarx.fields] [INFO   ] [2019-04-23 19:58:19,739] No compatible stix 1.2.0.6 mappings found. Loaded latest unchanged 1.2.0.5 field mappings.
No compatible stix 1.2.0.6 mappings found. Loaded latest unchanged 1.2.0.5 field mappings.
[stixmarx.fields] [INFO   ] [2019-04-23 19:58:19,842] No compatible cybox 2.1.0.17 mappings found. Loaded latest unchanged 2.1.0.16 field mappings.
No compatible cybox 2.1.0.17 mappings found. Loaded latest unchanged 2.1.0.16 field mappings.
[stixmarx.fields] [INFO   ] [2019-04-23 19:58:19,888] No compatible maec 4.1.0.14 mappings found. Loaded latest unchanged 4.1.0.13 field mappings.
No compatible maec 4.1.0.14 mappings found. Loaded latest unchanged 4.1.0.13 field mappings.
Stix - Convert1To2 - Conversion failed: Traceback (most recent call last):
  File "/home/george/TAXII_master/flask_webforms/app/stix_routes.py", line 163, in ConvertStix1ToStix2
    stix = elevate_string(uploadfile_data.read().decode('utf-8'))
  File "/usr/lib/python3.6/site-packages/stix2elevator/__init__.py", line 109, in elevate_string
    container = stixmarx.parse(io)
  File "/usr/lib/python3.6/site-packages/stixmarx/__init__.py", line 23, in parse
    stix_package = parser.parse_xml(xml_input, encoding)
  File "/usr/lib/python3.6/site-packages/stixmarx/parser.py", line 294, in parse_xml
    parser = MarkingParser(root=xml_input, encoding=encoding)
  File "/usr/lib/python3.6/site-packages/stixmarx/parser.py", line 78, in __init__
    self._root = xml.root(root, encoding)
  File "/usr/lib/python3.6/site-packages/stixmarx/xml.py", line 124, in root
    tree = to_etree(doc, encoding)
  File "/usr/lib/python3.6/site-packages/stixmarx/xml.py", line 111, in to_etree
    return etree.parse(doc, parser=parser)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1857, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```
If this is so, then I'll submit an issue over at `stixmarx`, because it should be a check on their end, but it might be good to check if `stixmarx` returns an `XMLSyntaxError` error, and report the known causes of that (such as the fact that there were no compatible mappings found), whether in the exceptions or in the messages. Here's the STIX 1 file I'm using:

[MAR-10135536.11.WHITE.stix.txt](https://github.com/oasis-open/cti-stix-elevator/files/3110390/MAR-10135536.11.WHITE.stix.txt)

**Comment by rpiazza** [comment]
Hi @arcsector,

I ran the elevator on this file locally, and had no problem.  Maybe this call didn't return anything?

elevate_string(uploadfile_data.read().decode('utf-8'))
