### ISSUE TITLE
Elevator seems to crash if given a non-existent file path, instead of giving an error message

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-elevator#207]
```/Users/rpiazza/py-envs/python3.7/bin/python /Users/rpiazza/git/stix/cti-stix-elevator/stix2elevator/cli.py /Users/rpiazza/git/stix/cti-stix-elevator/idioms-xml/list-as-string.xml --version 2.0 --missing-policy use-custom-properties --disable 901
Results produced by the stix2-elevator are not for production purposes.
Traceback (most recent call last):
  File "/Users/rpiazza/git/stix/cti-stix-elevator/stix2elevator/cli.py", line 200, in <module>
    main()
  File "/Users/rpiazza/git/stix/cti-stix-elevator/stix2elevator/cli.py", line 192, in main
    result = elevate(elevator_args.file_)
  File "/Users/rpiazza/git/stix/cti-stix-elevator/stix2elevator/__init__.py", line 72, in elevate
    container = stixmarx.parse(io)
  File "/Users/rpiazza/py-envs/python3.7/lib/python3.7/site-packages/stixmarx/__init__.py", line 25, in parse
    stix_package = parser.parse_xml(xml_input, encoding)
  File "/Users/rpiazza/py-envs/python3.7/lib/python3.7/site-packages/stixmarx/parser.py", line 294, in parse_xml
    parser = MarkingParser(root=xml_input, encoding=encoding)
  File "/Users/rpiazza/py-envs/python3.7/lib/python3.7/site-packages/stixmarx/parser.py", line 78, in __init__
    self._root = xml.root(root, encoding)
  File "/Users/rpiazza/py-envs/python3.7/lib/python3.7/site-packages/stixmarx/xml.py", line 124, in root
    tree = to_etree(doc, encoding)
  File "/Users/rpiazza/py-envs/python3.7/lib/python3.7/site-packages/stixmarx/xml.py", line 111, in to_etree
    return etree.parse(doc, parser=parser)
  File "src/lxml/etree.pyx", line 3469, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1856, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1```

**Comment by emmanvg** [comment]
Related to #159
